name: forkify_app
description: Um aplicativo mobile para pesquisar e gerenciar receitas favoritas usando a API do Forkify
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.6.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  dio: ^5.4.3+1
  sqflite: ^2.3.3+1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
